=begin

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

=end

def pentagonal_term(n)
    (n * ((3 * n) - 1))/2
end

def check_pentagonal(p)
    ((1 + Math.sqrt(1 + 24 * p))/6)
end

def is_pentagonal?(p)
    result = check_pentagonal(p)
    result % 1 == 0 ? result : false
end

def create_array_of_pents(max)
    array = []
    (1..max).to_a.each do |i|
        array << pentagonal_term(i)
    end
    array
end

def both_pentagonal?(a, b, array)
    a_val = array[a - 1]
    b_val = array[b - 1]
    is_pentagonal?(a_val + b_val) && is_pentagonal?((b_val - a_val).abs)
end

def find_answer(max)
    pents = create_array_of_pents(max)
    tries = 0
    max_diff = max - 1
    (1..max_diff).to_a.each do |difference|
        (1..max - difference).to_a.each do |first_index|
            tries += 1
            if both_pentagonal?(first_index, first_index + difference, pents)
                puts "#{pents[first_index - 1]}, #{pents[first_index + difference - 1]}"
                puts "Answer is #{pents[first_index + difference - 1] - pents[first_index - 1]}"
                break
            end
        end
    end
    puts "Made #{tries} comparisons"
end

start = Time.now
find_answer(2200)
p Time.now - start
